#Requires -Version 7.0
<#
.SYNOPSIS
    Detects modified XML views in the current git diff and generates a pre_migrate.py stub.
.PARAMETER RepoPath
    Path to the git repository / module. Defaults to current directory.
.PARAMETER TargetVersion
    Target Odoo version string for the migration folder (e.g. "18.0.1.5.0").
.PARAMETER EnterpriseSource
    Path to Enterprise source. Defaults to $cfg.EnterprisePath from config.local.yaml.
.OUTPUTS
    Exit 0 — No XML changes, or pre_migrate.py generated successfully
    Exit 1 — Error during generation
    Exit 3 — Environment error
#>
param(
    [string]$RepoPath         = ".",
    [Parameter(Mandatory)][string]$TargetVersion,
    [string]$EnterpriseSource = ""
)

Set-StrictMode -Version Latest

. "$PSScriptRoot\Get-OdooConfig.ps1"

if ([string]::IsNullOrWhiteSpace($EnterpriseSource)) {
    $EnterpriseSource = $cfg.EnterprisePath
}

if ([string]::IsNullOrWhiteSpace($EnterpriseSource)) {
    Write-Host "ERROR: Enterprise source not configured. Run setup-contributor.ps1 or pass -EnterpriseSource."
    exit 3
}

Write-Host ""
Write-Host "Pre-Migrate Generator"
Write-Host "─────────────────────────────────────────"
Write-Host "Repo:    $RepoPath"
Write-Host "Version: $TargetVersion"
Write-Host ""

# Get changed XML files from git diff
$changedFiles = git -C $RepoPath diff --name-only HEAD 2>&1
if ($LASTEXITCODE -ne 0) {
    # Try staged changes
    $changedFiles = git -C $RepoPath diff --cached --name-only 2>&1
}

$xmlFiles = $changedFiles | Where-Object { $_ -match '\.xml$' -and $_ -match 'views?/' }

if (-not $xmlFiles -or $xmlFiles.Count -eq 0) {
    Write-Host "✅ No XML view changes detected — pre_migrate.py not needed."
    exit 0
}

Write-Host "Found $($xmlFiles.Count) modified XML view file(s):"
$xmlFiles | ForEach-Object { Write-Host "   $_" }
Write-Host ""

# Extract xml:id values from modified XML files
$xmlIds = [System.Collections.Generic.List[string]]::new()
foreach ($xmlFile in $xmlFiles) {
    $fullPath = Join-Path $RepoPath $xmlFile
    if (-not (Test-Path $fullPath)) { continue }
    $content = Get-Content $fullPath -Raw
    $idMatches = [regex]::Matches($content, 'id\s*=\s*[''"]([a-z][a-z0-9_.]+)[''"]')
    foreach ($m in $idMatches) {
        $id = $m.Groups[1].Value
        if (-not $xmlIds.Contains($id)) { $xmlIds.Add($id) }
    }
}

if ($xmlIds.Count -eq 0) {
    Write-Host "⚠️  XML files found but no xml:id attributes extracted."
    exit 0
}

Write-Host "Extracted $($xmlIds.Count) xml:id(s):"
$xmlIds | ForEach-Object { Write-Host "   $_" }
Write-Host ""

# Search Enterprise source for each ID to find model name
$viewInfoList = [System.Collections.Generic.List[hashtable]]::new()
foreach ($xmlId in $xmlIds) {
    $shortId = $xmlId -replace '^[^.]+\.', ''  # remove module prefix
    $grepResult = Get-ChildItem -Path $EnterpriseSource -Filter "*.xml" -Recurse -ErrorAction SilentlyContinue |
        Select-String -Pattern "id\s*=\s*['""]$([regex]::Escape($shortId))['""]" -ErrorAction SilentlyContinue |
        Select-Object -First 1

    $modelName = "unknown.model"
    if ($grepResult) {
        $fileContent = Get-Content $grepResult.Path -Raw -ErrorAction SilentlyContinue
        if ($fileContent -match 'model\s*=\s*[''"]([a-z][a-z0-9_.]+)[''"]') {
            $modelName = $matches[1]
        }
    }
    $viewInfoList.Add(@{ Id = $xmlId; Model = $modelName })
}

# Generate pre_migrate.py content
$migrationsDir = Join-Path $RepoPath "migrations" $TargetVersion
New-Item -ItemType Directory -Force -Path $migrationsDir | Out-Null

$outputFile = Join-Path $migrationsDir "pre_migrate.py"

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# -*- coding: utf-8 -*-")
$lines.Add("# Auto-generated by pre-migrate-generator.ps1")
$lines.Add("# Review before deploying — verify model names and view IDs")
$lines.Add("")
$lines.Add("")
$lines.Add("def migrate(cr, version):")
$lines.Add("    if not version:")
$lines.Add("        return")
$lines.Add("")

foreach ($info in $viewInfoList) {
    $lines.Add("    # View: $($info.Id)")
    $lines.Add('    cr.execute("""')
    $lines.Add("        DELETE FROM ir_ui_view")
    $lines.Add("        WHERE name = '$($info.Id)'")
    $lines.Add("          AND model = '$($info.Model)'")
    $lines.Add('    """)')
    $lines.Add("")
}

$lines | Set-Content $outputFile -Encoding UTF8

Write-Host "✅ Generated: $outputFile"
Write-Host ""
Write-Host "⚠️  Review the generated file:"
Write-Host "   - Verify model names (marked 'unknown.model' if not found in Enterprise source)"
Write-Host "   - Verify view IDs match exactly"
Write-Host "   - Remove any entries for views that are not being replaced"
exit 0
